name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.JSONKEY}}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/$GCP_PROJECT_ID/springboot-app:$GITHUB_SHA .
        env:
          GCP_PROJECT_ID: kubernetes-456203

      - name: Push Docker Image
        run: |
          docker push gcr.io/$GCP_PROJECT_ID/springboot-app:$GITHUB_SHA
        env:
          GCP_PROJECT_ID: kubernetes-456203

      - name: Set up kubectl
        run: |
          gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1
          kubectl version

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
